version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:8.10
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'b9:35:de:ea:79:f4:1e:c9:16:04:89:d7:cc:d4:fc:39'
      - run:
          name: Setup SSH Key Host
          command: |
            ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Deploy
          command: |
            ssh $SSH_USER@$SSH_HOST "cd zoobc-explorer-api/ && chmod +x deploy.sh && ./deploy.sh"

workflows:
  version: 2
  build:
    jobs:
      - deploy
