version: 2.0

jobs:
  build:
    working_directory: ~/spinechain-explorer-prototype
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Setup Dependencies
          command: npm install
      - run:
          name: Run Test Local
          command: npm test
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

workflows:
  version: 2
  build:
    jobs:
      - build
